### ISSUE TITLE
Issues with Yarl

### ISSUE THREAD

**Issue by eyaadh** [uwinx/tamtam.py#7]
I am unable to go around this, trying this on Win 10 appreciate any assistance. 
```
(venv3.7) C:\Users\eyaadh\PycharmProjects\roanuedhuru_tamtam>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from tamtam import Bot, Dispatcher, run_poller
  File "C:\Users\eyaadh\PycharmProjects\roanuedhuru_tamtam\venv3.7\lib\site-packages\tamtam\__init__.py", line 1, in <module>
    from .api.bot import Bot
  File "C:\Users\eyaadh\PycharmProjects\roanuedhuru_tamtam\venv3.7\lib\site-packages\tamtam\api\bot.py", line 8, in <module>
    from .requests import Requester, UrlType
  File "C:\Users\eyaadh\PycharmProjects\roanuedhuru_tamtam\venv3.7\lib\site-packages\tamtam\api\requests.py", line 6, in <module>
    from yarl import URL, Query
ImportError: cannot import name 'Query' from 'yarl' (C:\Users\eyaadh\PycharmProjects\roanuedhuru_tamtam\venv3.7\lib\site-packages\yarl\__init__.py)

(venv3.7) C:\Users\eyaadh\PycharmProjects\roanuedhuru_tamtam>python --version
Python 3.7.4

(venv3.7) C:\Users\eyaadh\PycharmProjects\roanuedhuru_tamtam>pip show yarl
Name: yarl
Version: 1.3.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\users\eyaadh\pycharmprojects\roanuedhuru_tamtam\venv3.7\lib\site-packages
Requires: multidict, idna
Required-by: tamtampy, aiohttp

```

**Comment by uwinx** [comment]
Is this still relevant?

**Comment by uwinx** [comment]
Must be fixed now.
